---
- name: Create the Bilbo Kubernetes host
  ansible.builtin.import_playbook: machines-k0s.yml

- name: Prepare Bilbo test storage
  hosts: provisioned_machines
  become: true
  roles:
    - role: ../../erebor/roles/ceph_loop
