---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart dummy prefix
  ansible.builtin.systemd_service:
    name: amonsul-dummy.service
    enabled: true
    state: restarted

- name: Restart FRR
  ansible.builtin.service:
    name: frr
    state: restarted

