apiVersion: v1
data:
    token: ENC[AES256_GCM,data:3RBnmQfZr8GS+xFSvmWKF9JupIbXYxuFwZviZtk3NlUOM5VNHLwhM1Js5XzxTGzx,iv:Wc4/c79bLd2xkSwOMfWPeuHL/8FEQ3hDXYZYPWnTEQ4=,tag:AqrUrM99tjXn1YoierH4YA==,type:str]
    username: ENC[AES256_GCM,data:4Ecv3pT5I3Nvyz+G/nKYnw==,iv:jH7JKuuUOtWtOJ7/lctpxcpPgqRvGe5R7fwX0oj2734=,tag:Wc9Tfl+mCtO37Ph2mMuWwQ==,type:str]
kind: Secret
metadata:
    name: gondolin-example
    namespace: gondolin
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T07:31:13Z"
    mac: ENC[AES256_GCM,data:D8P3Py/Qgqvvap0sBZrxhdS6gdnCAyH/X6DD6uQtwtyd1UovTghV4a4qsS7ozuKZbHpRy9M29H7oOiMBFHo9NCvLS3RyyWzn/1oni4mpBen9jCqP7APfnrpiGLLVkjxdcy143tIYquZWtH6g1TnIVgGBM/TWANiWTjYOoDMhbbc=,iv:G3180fUxDmmCcb8TaB6DfOa4+w95TE6VMXBUP7VnngY=,tag:0/ICUyvkysIKOaX89PsuEA==,type:str]
    pgp:
        - created_at: "2026-07-30T07:31:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dm7M9TxCABZUSAQdA7oFFv3SKNKl8XOZ6cbd3jeQzmR/ilGVEydGk9Z0Abz4w
            ikc+/UtRd/nYIRqKILzf/1X1Z77EXlg3nq7dXC63aYrv56uWaGY06soN9apmcDm8
            1GgBCQIQfV8Kex6X9xq1DtPsIUYj0QDazkmUTrDnQDZ/1+vNlHuXDOxD4OdGXZgz
            Y7SBP7AeB4KR6a2203hDAn9rMKILAEwfYU7DVC7ga5LLJY3zEq2mN9Vk7Um2GOJz
            hMbWcPoaj3SIgA==
            =FFqC
            -----END PGP MESSAGE-----
          fp: FA258173726B7C714CE0585FC4BD402D294B23BE
    version: 3.13.2
