---
middleearth_dir: "{{ playbook_dir | dirname | dirname }}"
erebor_dir: "{{ middleearth_dir }}/erebor"

machine_container_image: local/erebor-machine:latest
machine_container_custom_build_context: "{{ erebor_dir }}/machine"
machine_container_custom_containerfile: "{{ erebor_dir }}/machine/Containerfile"
machine_container_kernel: "{{ erebor_dir }}/kernel/Image"
machine_container_ssh_private_key: >-
  {{ lookup('env', 'HOME') }}/.ssh/id_apple_machine
machine_container_ssh_public_key: "{{ machine_container_ssh_private_key }}.pub"
machine_container_recreate: false
machine_cpus: 4
machine_memory_gib: 8

k0s_version: v1.35.2+k0s.0
k0s_node_role: controller
k0s_controller_enable_worker: true
k0s_config_source: "{{ erebor_dir }}/machine/k0s.yaml"
kubeconfig_path: "{{ erebor_dir }}/machine/kubeconfig"

kernel_rebuild: false
imladris_users: []

