apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../treebeard
patches:
  - target:
      kind: Kustomization
      name: isengard-stack
    patch: |-
      - op: replace
        path: /spec/path
        value: ./isengard/stacks/overlays/saruman
