apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: isengard
  namespace: isengard
spec:
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              memory: 2Gi

