apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../wormtongue
labels:
  - pairs:
      isengard.middleearth.io/profile: treebeard
patches:
  - path: elasticsearch.yaml
  - path: kibana.yaml
