---
all:
  children:
    linux:
      hosts:
        example-vm:
          ansible_host: 192.0.2.10
          ansible_user: operator
      vars:
        imladris_users: []
    raspberry_pi:
      hosts: {}
      vars:
        raspberry_pi_prepare: true
    k0s_controllers:
      hosts:
        example-vm:
          k0s_controller_enable_worker: true
    k0s_workers:
      hosts: {}
    ovs_ovn:
      hosts: {}
      vars:
        ovs_ovn_install: true
    machine_hosts:
      children:
        lima_machines:
          hosts:
            imladris-lima:
              machine_backend: lima
              machine_name: imladris-lima
        container_machines:
          hosts:
            imladris-container:
              machine_backend: container
              machine_name: imladris-container
      vars:
        ansible_connection: local
