apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../thorin
patches:
  - target:
      kind: Kustomization
      name: platform-networking
    patch: |-
      - op: replace
        path: /spec/path
        value: ./apps/erebor/overlays/smaug/cilium
  - target:
      kind: Kustomization
      name: platform-ingress
    patch: |-
      - op: replace
        path: /spec/path
        value: ./apps/erebor/overlays/smaug/traefik
  - target:
      kind: Kustomization
      name: erebor-rook-ceph
    patch: |-
      - op: replace
        path: /spec/path
        value: ./apps/erebor/overlays/smaug/rook-ceph

