apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: isengard
spec:
  version: 9.2.2
  count: 1
  elasticsearchRef:
    name: isengard
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi

