apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik-crds
  interval: 10m
  path: ./khazad-dum/infrastructure/base/cilium
  prune: true
  sourceRef:
    kind: GitRepository
    name: khazad-dum
  timeout: 10m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
  interval: 10m
  path: ./khazad-dum/infrastructure/base/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: khazad-dum
  timeout: 10m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./khazad-dum/infrastructure/base/traefik-crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: khazad-dum
  timeout: 10m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
    - name: traefik-crds
  interval: 10m
  path: ./khazad-dum/infrastructure/base/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: khazad-dum
  timeout: 10m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
  interval: 10m
  path: ./khazad-dum/infrastructure/base/metrics
  prune: true
  sourceRef:
    kind: GitRepository
    name: khazad-dum
  timeout: 10m
  wait: true
