apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium-system
spec:
  values:
    enableHostFirewall: false
    l7Proxy: true
    envoy:
      enabled: true
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
