apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privileged-containers
spec:
  admission: true
  background: true
  validationFailureAction: Audit
  rules:
    - name: validate-privileged
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        allowExistingViolations: true
        message: "Privileged containers should not be used."
        foreach:
          - list: request.object.spec.containers
            deny:
              conditions:
                any:
                  - key: "{{ element.securityContext.privileged || `false` }}"
                    operator: Equals
                    value: true

