---
all:
  children:
    machine_hosts:
      children:
        container_machines:
          hosts:
            erebor:
              machine_backend: container
              machine_name: erebor
      vars:
        ansible_connection: local

