apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../bilbo
patches:
  - target:
      kind: Kustomization
      name: cilium
    patch: |-
      - op: replace
        path: /spec/path
        value: ./erebor/gitops/infra/overlays/thorin/cilium
  - target:
      kind: Kustomization
      name: traefik
    patch: |-
      - op: replace
        path: /spec/path
        value: ./erebor/gitops/infra/overlays/thorin/traefik
  - target:
      kind: Kustomization
      name: rook-ceph
    patch: |-
      - op: replace
        path: /spec/path
        value: ./erebor/gitops/infra/overlays/thorin/rook-ceph
