apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../bilbo
patches:
  - target:
      kind: Kustomization
      name: platform-networking
    patch: |-
      - op: replace
        path: /spec/path
        value: ./khazad-dum/apps/erebor/overlays/thorin/cilium
  - target:
      kind: Kustomization
      name: platform-ingress
    patch: |-
      - op: replace
        path: /spec/path
        value: ./khazad-dum/apps/erebor/overlays/thorin/traefik
  - target:
      kind: Kustomization
      name: erebor-rook-ceph
    patch: |-
      - op: replace
        path: /spec/path
        value: ./khazad-dum/apps/erebor/overlays/thorin/rook-ceph
